<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>GuestHouse Manager</title>
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">


</head>
<body>
<div class="wrap">
    <header>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark"
                 style="background-color: rgba(233, 236, 239, 0.8);">
                <a class="navbar-brand" href="/">GuestHouse Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Strona główna </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/all-rooms">Wszystkie pokoje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/add-room">Dodaj pokój</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/customer-search">Szukaj klienta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout">Wyloguj</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>