<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>GuestHouse Manager</title>
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../../css/availability-calendar.css" rel="stylesheet" type="text/css">
    <style>
        body {
            font-family: 'Open Sans';
            background-color: #ECF0F1;
        }

        .container {
            max-width: 60%;
            margin: 150px auto;
        }
    </style>

</head>
<body>
<div class="wrap">
    <header>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark"
                 style="background-color: rgba(233, 236, 239, 0.8);">
                <a class="navbar-brand" href="/all-rooms">GuestHouse Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="/all-rooms">Strona główna </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Logowanie</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>